"""Device provider protocol."""

from __future__ import annotations

from typing import Protocol


class DeviceProvider(Protocol):
    def reset_app(self, episode_id: str | None = None) -> None: ...
    def click_resource(self, resource_name: str) -> None: ...
    def input_resource(self, resource_name: str, text: str) -> None: ...
    def press_back(self) -> None: ...
    def read_shared_prefs(self) -> str: ...
